extensions:
  universal-editor/ui/1:
    $include: src/universal-editor-ui-1/ext.config.yaml
  aem/cf-console-admin/1:
    operations:
      view:
        - type: web
          impl: index.html#/cf-admin-console
    actions: actions
    web: src/universal-editor-ui-1/web-src
    hooks:
      pre-app-run: nod.e node_modules/@adobe/uix-guest/scripts/generate-metadata.js
      pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
      post-app-deploy: ./hooks/post-deploy.js


    