operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    aem-contenthub-assets-details-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            IMS_ENDPOINT: $IMS_ENDPOINT
            METASCOPES: $METASCOPES
            TECHNICAL_ACCOUNT_CLIENT_ID: $TECHNICAL_ACCOUNT_CLIENT_ID
            TECHNICAL_ACCOUNT_CLIENT_SECRET: $TECHNICAL_ACCOUNT_CLIENT_SECRET
            TECHNICAL_ACCOUNT_EMAIL: $TECHNICAL_ACCOUNT_EMAIL
            TECHNICAL_ACCOUNT_ID: $TECHNICAL_ACCOUNT_ID
            ORGANIZATION_ID: $ORGANIZATION_ID
            PRIVATE_KEY: $PRIVATE_KEY
            PUBLIC_KEY: $PUBLIC_KEY
            CERTIFICATE_EXPIRATION_DATE: $CERTIFICATE_EXPIRATION_DATE
            WORKFRONT_BASE_URL: $WORKFRONT_BASE_URL
            AEM_AUTHOR: $AEM_AUTHOR
            DOCUMENT_PROVIDER_ID: $DOCUMENT_PROVIDER_ID
            DEFAULT_PROJECT_ID: $DEFAULT_PROJECT_ID
          annotations:
            require-adobe-auth: false
            final: true
