operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    aem-contenthub-assets-details-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            API_ENDPOINT: $API_ENDPOINT
          annotations:
            require-adobe-auth: false
            final: true
