operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    universal-editor-richtext-draft:
      license: Apache-2.0
      actions:
        list-branches:
          function: actions/list-branches/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
