operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    aem-cf-editor-1:
      license: Apache-2.0
      actions:
        get-user-groups:
          function: actions/get-user-groups/index.js
          web: 'yes'
          runtime: nodejs:18
          require-adobe-auth: false
          inputs:
            LOG_LEVEL: debug
          annotations:
            final: true
hooks:
  pre-app-run: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  post-app-deploy: ./hooks/post-deploy.js
