name: Deploy steps for "cf-console-action-bar-button-sample"

on:
  workflow_call:
    inputs:
      test: 
        description: 'Test'
        required: false
        type: string
    secrets:
      test: 
          description: 'Test'
          required: false

jobs:
    install-deps:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            echo "Installing dependencies in cf-console-action-bar-button-sample"
            npm install
