name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  find-changed-dirs:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories }} # The `dirs` doesn't exist in the outputs of changed-files@v35 action.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_max_depth: 2 # This is optional. If not provided, full subdirectories' paths will be provided. Use it if you need to trim the output. See docs for details: https://github.com/tj-actions/changed-files/tree/main#inputs.
          json: true
          quotepath: false

      - name: "Set output in the matrix format"
        id: set-output
        run: echo "changed_directories={\"dir\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  install-deps:
    runs-on: ubuntu-latest
    if: ${{ needs.find-changed-dirs.outputs.changed_directories != '' }} # Without it, the strategy parser will fail if the changed_directories is empty.
    strategy:
      matrix: ${{fromJson(needs.find-changed-dirs.outputs.changed_directories)}}
    needs:
      - find-changed-dirs
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Replace dash with underscore in matrix variable
        env:
          ORIGINAL_STRING: ${{ matrix.dir }}
        run: |
          NEW_STRING=${ORIGINAL_STRING//-/_}
          UPPER_CASE_STRING=$(echo "$NEW_STRING" | tr '[:lower:]' '[:upper:]')
          echo "New string >>: $NEW_STRING"
      - name: Test
        run: echo ${{ env.GITHUB_SHA_SHORT }}
      - name: Test1
        run: |
          echo "Secret env value: ${{ secrets[format('{0}', env.GITHUB_SHA_SHORT)] }}"
      - name: create env file
        working-directory: ${{ matrix.dir }}
        run: |
          # echo "Current directory: $(pwd)"
          touch .env
          echo "${{ secrets[format('{0}', env.GITHUB_SHA_SHORT)] }}" >> .env
          cat .env
      - working-directory: ${{ matrix.dir }}
        run: |
          if [ -f package.json ]; then
            echo "Installing dependencies in ${{ matrix.dir }}"
            npm install
          else
            exit 0
          fi
      - name: Setup AIO CLI
        working-directory: ${{ matrix.dir }}
        run: |
          # echo "Current directory: $(pwd)"
          npm install -g @adobe/aio-cli
      - name: deploy to prod
        working-directory: ${{ matrix.dir }}
        run: |
          # echo "Current directory: $(pwd)"
          aio app deploy --web-optimize --no-publish
