name: AIO App CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['20']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
        working-directory: ./cf-console-action-bar-button-sample
      - name: aio install
        run: npm install -g @adobe/aio-cli
        working-directory: ./cf-console-action-bar-button-sample
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Auth
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: oauth_sts
          CLIENTID: ${{ secrets.CLIENTID_STAGE }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET_STAGE }}
          TECHNICALACCOUNTID: ${{ secrets.TECHNICALACCID_STAGE }}
          TECHNICALACCOUNTEMAIL: ${{ secrets.TECHNICALACCOUNTEMAIL_STAGE }}
          IMSORGID: ${{ secrets.IMSORGID_STAGE }}
          SCOPES: ${{ secrets.SCOPES_STAGE }}
      # - name: Build
      #   env:
      #     AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
      #   uses: adobe/aio-apps-action@3.3.0
      #   with:
      #     working-directory: ./cf-console-action-bar-button-sample #not merged
      #     os: ${{ matrix.os }}
      #     command: build
      - name: deploy
        run: aio app deploy
        working-directory: ./cf-console-action-bar-button-sample
      # - name: Deploy
      #   env:
      #     AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
      #     AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_STAGE }}
      #     AIO_PROJECT_ID: ${{ secrets.AIO_PROJECT_ID_STAGE }}
      #     AIO_PROJECT_NAME: ${{ secrets.AIO_PROJECT_NAME_STAGE }}
      #     AIO_PROJECT_ORG_ID: ${{ secrets.AIO_PROJECT_ORG_ID_STAGE }}
      #     AIO_PROJECT_WORKSPACE_ID: ${{ secrets.AIO_PROJECT_WORKSPACE_ID_STAGE }}
      #     AIO_PROJECT_WORKSPACE_NAME: ${{ secrets.AIO_PROJECT_WORKSPACE_NAME_STAGE }}
      #     AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ secrets.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES_STAGE }}
      #   uses: adobe/aio-apps-action@3.3.0
      #   with:
      #     working-directory: ./cf-console-action-bar-button-sample
      #     os: ${{ matrix.os }}
      #     command: deploy
      #     noPublish: true